AWSTemplateFormatVersion: '2010-09-09'
Resources:
  RightslineEventBus:
    Type: AWS::Events::EventBus
    Properties:
      EventSourceName: aws.partner/rightsline.com/${{ vars.ENVIRONMENT }}-div191-v4
      Name: aws.partner/rightsline.com/${{ vars.ENVIRONMENT }}-div191-v4
  RightslineRule:
    Type: AWS::Events::Rule
    Properties:
      Name: wb-rule-uk-poc-useast-Rightsline-events
      EventBusName: !Ref RightslineEventBus
      EventPattern:
        source:
          -aws.partner/Rightsline.${{ vars.ENVIRONMENT }}.com
      Targets:
        - Arn: !GetAtt RightslineLogGroup.Arn
          Id: RightslineTarget
  RightslineLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/events/${RightslineEventBus}
