name: Create EventBridge Event Bus
 
on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

jobs:
  create-event-bus:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Replace with your desired AWS region

      - name: Set Environment Variable
        run: |
          echo "{\"Environment\":\"stg\"}" > parameters.json # Set the environment to 'stg', 'dev', or 'prd'
        shell: bash

      - name: Deploy Event Bus
        run: |
          aws cloudformation deploy \
            --template-file testing14.yml \
            --stack-name rightsline-staging-event-bus-stack \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides Environment=$(cat parameters.json | jq -r .Environment) # Use the environment from the parameter file
        shell: bash
