name: Creating the Rightsline Infrastructure
on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

jobs:
  create-event-bus:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        id: aws-config
        run: |
          environment="${{ secrets.AWS_ENVIRONMENT }}"  # Get the environment from the secret

          if [ "$environment" == 'stg' ]; then
            echo "Setting up AWS credentials for STG environment"
            aws_access_key_id="${{ secrets.AWS_ACCESS_KEY_ID }}"
            aws_secret_access_key="${{ secrets.AWS_SECRET_ACCESS_KEY }}"

          elif [ "$environment" == 'prd']; then
            echo "Setting up AWS credentials for PRD environment"
            aws_access_key_id="${{ secrets.AWS_PRD_ACCESS_KEY_ID }}"
            aws_secret_access_key="${{ secrets.AWS_PRD_SECRET_ACCESS_KEY }}"

          else
            echo "Setting up AWS credentials for DEV environment"
            aws_access_key_id="${{ secrets.AWS_DEV_ACCESS_KEY_ID }}"
            aws_secret_access_key="${{ secrets.AWS_DEV_SECRET_ACCESS_KEY }}"

      - name: Deploy Event Bus
        run: |
          aws cloudformation deploy \
            --template-file testing14.yml \
            --stack-name rightsline-event-bus-stack \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides EventBusName=MyCustomEventBus Environment_details=$environment
