name: Creating the Rightsline Infrastructure
on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

jobs:
  create-event-bus:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        id: aws-config
        run: |
          current_branch=$(git branch --show-current)
          echo "Current branch is $current_branch"

          if [ current_branch == 'main']; then
            echo "Setting up AWS credentials for PRD environment"
            aws_access_key_id="${{ secrets.AWS_ACCESS_KEY_ID }}"
            aws_secret_access_key="${{ secrets.AWS_SECRET_ACCESS_KEY }}"

          elif [ current_branch == 'development']; then
            echo "Setting up AWS credentials for DEV environment"
            aws_access_key_id="${{ secrets.AWS_ACCESS_KEY_ID }}"
            aws_secret_access_key="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          
          else
            echo "Environment does not belongs to main or development"

          fi
          echo "AWS_ACCESS_KEY_ID=$aws_access_key_id" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=$aws_secret_access_key" >> $GITHUB_ENV
          aws configure set aws_access_key_id $aws_access_key_id
          aws configure set aws_secret_access_key $aws_secret_access_key
          aws configure set default.region us-east-1 # Replace with your desired AWS region

      - name: Deploy Event Bus
        run: |
          aws cloudformation deploy \
            --template-file testing14.yml \
            --stack-name rightsline-event-bus-stack \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides EventBusName=MyCustomEventBus Environment_details=$environment
