name: Create EventBridge Event Bus

on:
  push:
    branches:
      - main

jobs:
  create-event-bus:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Replace with your desired AWS region

      - name: Read environment from environment.json
        id: read-env
        run: echo ::set-output name=Environment::$(jq -r '.Environment' environment.json)

      - name: Select EventSourceName
        id: select-event-source
        run: |
          case "${{ steps.read-env.outputs.Environment }}" in
            "stg")
              echo "::set-output name=EventSourceName::aws.partner/rightsline.com/stg-div191-v4"
              ;;
            "dev")
              echo "::set-output name=EventSourceName::aws.partner/rightsline.com/dev-div191-v4"
              ;;
            "prd")
              echo "::set-output name=EventSourceName::aws.partner/rightsline.com/prd-div191-v4"
              ;;
          esac

      - name: Deploy Event Bus
        run: |
          aws cloudformation deploy \
            --template-file testing14.yml \
            --stack-name event-bus-stack \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides EventBusName=MyCustomEventBus EventSourceName=${{ steps.select-event-source.outputs.EventSourceName }}
